name: Required PR Tests
on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-pr-tests:
    runs-on: ubuntu-latest
    steps:
      # Check out repo under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      - name: build plugin
        run: ./gradlew build
